trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: |
    npm install -g @ionic/cli
    npm install
    ionic build
    npx cap copy android
    cd android
    ./gradlew assembleDebug
  displayName: 'Build APK and Copy to Artifacts'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(System.DefaultWorkingDirectory)/android/app/build/outputs/apk/debug'
    artifactName: 'apk'
    publishLocation: 'Container'
