trigger:
- main  

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @ionic/cli
    npm install
    ionic build
    ionic capacitor copy android || (echo "Failed to copy to Android directory"; exit 1)
    cd android || (echo "Android directory not found"; exit 1)
    ./gradlew assembleDebug || (echo "Failed to execute gradlew"; exit 1)
  displayName: 'Build APK'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(System.DefaultWorkingDirectory)/android/app/build/outputs/apk/debug'
    artifactName: 'apk'
    publishLocation: 'Container'
