
trigger:
- main  

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @ionic/cli
    npm install
    ionic build
    npx cap copy android
    cd android
    ./gradlew assembleDebug  # Build APK using Gradle
  displayName: 'Build APK'


- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(System.DefaultWorkingDirectory)/android/app/build/outputs/apk/debug'
    artifactName: 'apk'
    publishLocation: 'Container'



